//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernTests.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paragraph
    {
        public Paragraph()
        {
            this.Paragraphs1 = new HashSet<Paragraph>();
            this.Questions = new HashSet<Question>();
        }
    
        public int Id { get; set; }
        public int Number { get; set; }
        public string Text { get; set; }
        public int DocumentId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> ParagraphId { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual ICollection<Paragraph> Paragraphs1 { get; set; }
        public virtual Paragraph Paragraph1 { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual Section Section { get; set; }
    }
}
