//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernTests.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Tests = new HashSet<Test>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public Nullable<int> ParagraphId { get; set; }
        public Nullable<int> ParagraphsMarkIn { get; set; }
        public Nullable<int> ParagraphsMarkOut { get; set; }
        public Nullable<int> VoltageClass { get; set; }
        public string Category { get; set; }
        public string ImageUrl { get; set; }
        public string Title { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string AnswerDescription { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Paragraph Paragraph { get; set; }
        public virtual ICollection<Test> Tests { get; set; }
    }
}
